name: Build+Test+Release

on:
  push:
   tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # 設定 NuGet，確保舊式 packages.config 能還原
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: NuGet restore
        run: nuget restore .\SecsTest.sln

      # 設定 MSBuild (Visual Studio Build Tools)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild .\SecsTest.sln /p:Configuration=Release /m

      # 用 VSTest 跑 MSTest 測試
      - name: Run MSTest via VSTest
        run: |
          $testDlls = Get-ChildItem -Recurse -Filter *Tests.dll | Where-Object { $_.FullName -like "*\bin\Release\*" }
          foreach ($dll in $testDlls) {
            & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" $dll.FullName
          }
          
      - name: 壓縮執行檔
        run: |
          mkdir output
          copy SecsTest\bin\Release\* output\
          powershell Compress-Archive -Path output\* -DestinationPath SecsTest.zip

      - name: 發佈 Release
        uses: softprops/action-gh-release@v1
        with:
          files: SecsTest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

